/*
 * NewShopping.java
 *
 * Created on November 25, 2015, 9:29 AM
 */

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  rs748
 */
public class NewShopping extends javax.swing.JFrame {
    
    Connection conn = null;
    Statement statement = null;
    ResultSet resultSet = null;
    ResultSet resultSet2 = null;
    int count = 1;
    int size = 0;
    char cstatus = ' ';
    
    /** Creates new form NewShopping */
    public NewShopping() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Cart");

        jLabel1.setText("Customer ID:");

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Transaction ID:");

        jTextField2.setEditable(false);

        jComboBox1.setEditable(true);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setText("PRODUCT:");

        jLabel4.setText("QUANTITY:");

        jTextField3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField3InputMethodTextChanged(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jComboBox2.setEditable(true);
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jComboBox3.setEditable(true);
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jComboBox4.setEditable(true);
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel5.setText("Select Card:");

        jComboBox5.setEditable(true);

        jLabel6.setText("Select Address:");

        jComboBox6.setEditable(true);

        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Price/Unit:");

        jLabel16.setText("TOTAL CART VALUE :");

        jTextField7.setText("0");

        jMenu1.setText("Customer Operations");

        jMenuItem1.setText("Add Customer");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit Customer");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Shopping");

        jMenuItem3.setText("New Shopping Cart");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Transaction History");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Report Generation");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 165, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField6)
                            .addComponent(jTextField5)
                            .addComponent(jTextField4))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jButton2)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox5, 0, 224, Short.MAX_VALUE)))
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        dispose();
        AddCustomer AC = new AddCustomer();
        AC.setVisible(true);
    }                                       

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        dispose();
        EditCustomer EC = new EditCustomer();
        EC.setVisible(true);
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            resultSet = statement.executeQuery("select * from CUSTOMER where CID = \'"+ jTextField1.getText() +"\'");
            
            if(resultSet.next())
            {
                //Get the Customer Status
                cstatus = resultSet.getString(4).charAt(0);
                
                //Get Next CartID Generated
                int cartNum = 10001;
                resultSet = statement.executeQuery("select * from CART");
                while(resultSet.next())
                {
                    cartNum++;
                }
                jTextField2.setText(""+cartNum);
                
                //Get the CCNumber for the Customer
                resultSet = statement.executeQuery("select CCNumber from STORED_CARD where CID = \'"+ jTextField1.getText() +"\'");
                while(resultSet.next())
                {
                    jComboBox5.addItem(resultSet.getString(1));
                }
                
                //Get the Shipping Address Name for the Customer
                resultSet = statement.executeQuery("select SANAME from SHIP_ADDRESS where CID = \'"+ jTextField1.getText() +"\'");
                while(resultSet.next())
                {
                    jComboBox6.addItem(resultSet.getString(1));
                }
                
                //Populate all the Product Names
                resultSet = statement.executeQuery("select PNAME from PRODUCT ");
                while(resultSet.next())
                {
                    jComboBox1.addItem(resultSet.getString(1));
                    jComboBox2.addItem(resultSet.getString(1));
                    jComboBox3.addItem(resultSet.getString(1));
                    jComboBox4.addItem(resultSet.getString(1));
                }
                
                jTextField1.setEditable(false);
                jButton1.setEnabled(false);
                jButton2.setEnabled(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
            }
            else
            {
                //Display No record found
                JOptionPane.showMessageDialog(null, "Customer ID \""+jTextField1.getText()+"\" does not Exists.");
            }

            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                        

    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        dispose();
        TransactionHistory TH = new TransactionHistory();
        TH.setVisible(true);
    }                                       

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        dispose();
        ReportGeneration RG = new ReportGeneration();
        RG.setVisible(true);
    }                                   

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                        
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            resultSet = statement.executeQuery("select PID, PPRICE from PRODUCT where PNAME = \'"+ jComboBox1.getSelectedItem().toString() +"\'");
            
            if(resultSet.next())
            {
                jLabel7.setText(resultSet.getString(1));
                String cost = resultSet.getString(2);
                //Price for Gold and Platinum customer from offer if its there.
                if(cstatus == 'G' || cstatus == 'P')
                {
                    resultSet2 = statement.executeQuery("select OFFERPRICE from OFFER_PRODUCT where PID = \'"+ jLabel7.getText() +"\'");
                    if(resultSet2.next())
                    {
                        jLabel12.setText(resultSet2.getString(1));
                    }
                    else
                    {
                        jLabel12.setText(cost);
                    }
                    resultSet2.close();
                }
                else
                {
                    jLabel12.setText(cost);
                }
                jLabel7.setVisible(true);
            }
            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                                       

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                        
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            resultSet = statement.executeQuery("select PID, PPRICE from PRODUCT where PNAME = \'"+ jComboBox2.getSelectedItem().toString() +"\'");
            
            if(resultSet.next())
            {
                jLabel8.setText(resultSet.getString(1));
                String cost = resultSet.getString(2);
                //Price for Gold and Platinum customer from offer if its there.
                if(cstatus == 'G' || cstatus == 'P')
                {
                    resultSet2 = statement.executeQuery("select OFFERPRICE from OFFER_PRODUCT where PID = \'"+ jLabel8.getText() +"\'");
                    if(resultSet2.next())
                    {
                        jLabel13.setText(resultSet2.getString(1));
                    }
                    else
                    {
                        jLabel13.setText(cost);
                    }
                    resultSet2.close();
                }
                else
                {
                    jLabel13.setText(cost);
                }
                jLabel8.setVisible(true);
            }
            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                                       

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                        
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            resultSet = statement.executeQuery("select PID, PPRICE from PRODUCT where PNAME = \'"+ jComboBox3.getSelectedItem().toString() +"\'");
            
            if(resultSet.next())
            {
                jLabel9.setText(resultSet.getString(1));
                String cost = resultSet.getString(2);
                //Price for Gold and Platinum customer from offer if its there.
                if(cstatus == 'G' || cstatus == 'P')
                {
                    resultSet2 = statement.executeQuery("select OFFERPRICE from OFFER_PRODUCT where PID = \'"+ jLabel9.getText() +"\'");
                    if(resultSet2.next())
                    {
                        jLabel14.setText(resultSet2.getString(1));
                    }
                    else
                    {
                        jLabel14.setText(cost);
                    }
                    resultSet2.close();
                }
                else
                {
                    jLabel14.setText(cost);
                }
                jLabel9.setVisible(true);
            }
            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                                       

    private void jComboBox4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                        
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            resultSet = statement.executeQuery("select PID, PPRICE from PRODUCT where PNAME = \'"+ jComboBox4.getSelectedItem().toString() +"\'");
            
            if(resultSet.next())
            {
                jLabel10.setText(resultSet.getString(1));
                String cost = resultSet.getString(2);
                //Price for Gold and Platinum customer from offer if its there.
                if(cstatus == 'G' || cstatus == 'P')
                {
                    resultSet2 = statement.executeQuery("select OFFERPRICE from OFFER_PRODUCT where PID = \'"+ jLabel10.getText() +"\'");
                    if(resultSet2.next())
                    {
                        jLabel15.setText(resultSet2.getString(1));
                    }
                    else
                    {
                        jLabel15.setText(cost);
                    }
                    resultSet2.close();
                }
                else
                {
                    jLabel15.setText(cost);
                }
                jLabel10.setVisible(true);
            }
            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                                       

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
            //Connect to server
            conn = DriverManager.getConnection("jdbc:mysql://sql2.njit.edu/rs748?" + "user=rs748&password=O2cYL83NM");
            // Statements allow to issue SQL queries to the database
            statement = conn.createStatement();
            //String to hold the Query
            String SQL = "";
            String SQL2 = "";
            
            SQL = "INSERT INTO CART VALUES ("+ jTextField2.getText()+ ", \'" + jTextField1.getText() + "\', \'" 
                    + jComboBox6.getSelectedItem().toString() + "\', \'" +jComboBox5.getSelectedItem().toString() 
                    + "\', \'Pending\', CURDATE() )";
            
            statement.executeUpdate(SQL);
            
            if(jLabel7.isVisible())
            {
                    SQL2 = "INSERT INTO APPEARS_IN VALUES ("+ jTextField2.getText()+ ", \'" + jLabel7.getText() + "\', " 
                        + jTextField3.getText() + ", " + jLabel12.getText() + ")";
                    statement.executeUpdate(SQL2);
            }
            
            if(jLabel8.isVisible())
            {
                    SQL2 = "INSERT INTO APPEARS_IN VALUES ("+ jTextField2.getText()+ ", \'" + jLabel8.getText() + "\', " 
                        + jTextField4.getText() + ", " + jLabel13.getText() + ")";
                    statement.executeUpdate(SQL2);
            }
            
            if(jLabel9.isVisible())
            {
                    SQL2 = "INSERT INTO APPEARS_IN VALUES ("+ jTextField2.getText()+ ", \'" + jLabel9.getText() + "\', " 
                        + jTextField5.getText() + ", " + jLabel14.getText() + ")";
                    statement.executeUpdate(SQL2);
            }
            
            if(jLabel10.isVisible())
            {
                    SQL2 = "INSERT INTO APPEARS_IN VALUES ("+ jTextField2.getText()+ ", \'" + jLabel10.getText() + "\', " 
                        + jTextField6.getText() + ", " + jLabel15.getText() + ")";
                    statement.executeUpdate(SQL2);
            }
            
            jTextField1.setEditable(true);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            jComboBox5.removeAllItems();
            jComboBox6.removeAllItems();
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            

            resultSet.close();
            statement.close();
            conn.close();
        } catch (SQLException ex) {
            // handle any errors
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        }
    }                                        

    private void jTextField3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        try
        {
            float value = 0;
            float cost;
            float quantity;
            float ProductBill;
            if(jLabel7.isVisible())
            {
                cost = Float.parseFloat(jLabel12.getText());
                quantity = Float.parseFloat(jTextField3.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel8.isVisible())
            {
                cost = Float.parseFloat(jLabel13.getText());
                quantity = Float.parseFloat(jTextField4.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel9.isVisible())
            {
                cost = Float.parseFloat(jLabel14.getText());
                quantity = Float.parseFloat(jTextField5.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel10.isVisible())
            {
                cost = Float.parseFloat(jLabel15.getText());
                quantity = Float.parseFloat(jTextField6.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            jTextField7.setText(""+(value));
        }
        catch (NumberFormatException e)
        {     
            //Number Exception for blank text box
        }
    }                                       

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        try
        {
            float value = 0;
            float cost;
            float quantity;
            float ProductBill;
            if(jLabel7.isVisible())
            {
                cost = Float.parseFloat(jLabel12.getText());
                quantity = Float.parseFloat(jTextField3.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel8.isVisible())
            {
                cost = Float.parseFloat(jLabel13.getText());
                quantity = Float.parseFloat(jTextField4.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel9.isVisible())
            {
                cost = Float.parseFloat(jLabel14.getText());
                quantity = Float.parseFloat(jTextField5.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel10.isVisible())
            {
                cost = Float.parseFloat(jLabel15.getText());
                quantity = Float.parseFloat(jTextField6.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            jTextField7.setText(""+(value));
        }
        catch (NumberFormatException e)
        {     
            //Number Exception for blank text box
        }
    }                                       

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        try
        {
            float value = 0;
            float cost;
            float quantity;
            float ProductBill;
            if(jLabel7.isVisible())
            {
                cost = Float.parseFloat(jLabel12.getText());
                quantity = Float.parseFloat(jTextField3.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel8.isVisible())
            {
                cost = Float.parseFloat(jLabel13.getText());
                quantity = Float.parseFloat(jTextField4.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel9.isVisible())
            {
                cost = Float.parseFloat(jLabel14.getText());
                quantity = Float.parseFloat(jTextField5.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel10.isVisible())
            {
                cost = Float.parseFloat(jLabel15.getText());
                quantity = Float.parseFloat(jTextField6.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            jTextField7.setText(""+(value));
        }
        catch (NumberFormatException e)
        {     
            //Number Exception for blank text box
        }
    }                                       

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        try
        {
            float value = 0;
            float cost;
            float quantity;
            float ProductBill;
            if(jLabel7.isVisible())
            {
                cost = Float.parseFloat(jLabel12.getText());
                quantity = Float.parseFloat(jTextField3.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel8.isVisible())
            {
                cost = Float.parseFloat(jLabel13.getText());
                quantity = Float.parseFloat(jTextField4.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel9.isVisible())
            {
                cost = Float.parseFloat(jLabel14.getText());
                quantity = Float.parseFloat(jTextField5.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            if(jLabel10.isVisible())
            {
                cost = Float.parseFloat(jLabel15.getText());
                quantity = Float.parseFloat(jTextField6.getText());
                ProductBill = cost * quantity;
                value += ProductBill;
            }
            jTextField7.setText(""+(value));
        }
        catch (NumberFormatException e)
        {     
            //Number Exception for blank text box
        }
    }                                       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewShopping().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration                   
    
}